Token: "MTA0NDcwMDQxOTEyMjc5MDQzMQ.Gk4q7I.f3GuWewndYJZByNIkoA90FmhnwZNKrQhMrdUH4"
Bot_prefix: "!"
temp_music_channel: "1045075344299937792"
GOOGLE_API_KEY: 'AIzaSyBQfwI0U0f5lAzgP_UuDns9eeGOz3YsRWA'